/**
 * Emits supabase/seed.sql from the TypeScript seed data.
 *
 * Generated rather than hand-written so the database seed cannot drift from
 * src/data/*.ts. Re-run with `npm run db:generate-seed` after changing the seed.
 *
 * The output is idempotent: every insert is an upsert keyed on the natural id,
 * so applying it twice leaves the same rows.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { events } from '../src/data/events';
import { reviews } from '../src/data/reviews';
import { venues } from '../src/data/venues';
import type { Review, Venue } from '../src/types';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'supabase', 'seed.sql');

/** Single-quote a string for SQL, or emit NULL. */
function q(v: string | null | undefined): string {
  if (v === null || v === undefined) return 'NULL';
  return `'${v.replace(/'/g, "''")}'`;
}

function n(v: number | null | undefined): string {
  return v === null || v === undefined || Number.isNaN(v) ? 'NULL' : String(v);
}

function b(v: boolean | null | undefined): string {
  return v === null || v === undefined ? 'NULL' : v ? 'true' : 'false';
}

/** jsonb literal. */
function j(v: unknown): string {
  return `${q(JSON.stringify(v ?? null))}::jsonb`;
}

/** text[] literal. */
function arr(v: string[] | undefined): string {
  if (!v || v.length === 0) return `'{}'::text[]`;
  return `ARRAY[${v.map(q).join(', ')}]::text[]`;
}

function enumArr(v: string[] | undefined, type: string): string {
  if (!v || v.length === 0) return `'{}'::${type}[]`;
  return `ARRAY[${v.map(q).join(', ')}]::${type}[]`;
}

const lines: string[] = [];

lines.push('-- Generated by scripts/generate-seed-sql.ts. Do not edit by hand.');
lines.push('-- Regenerate with: npm run db:generate-seed');
lines.push('--');
lines.push(`-- ${venues.length} venues, ${reviews.length} reviews, ${events.length} events.`);
lines.push('');
lines.push('begin;');
lines.push('');

/* ------------------------------------------------------------------ venues */

lines.push('-- Venues. Inserted in two passes because closure_successor_id is a');
lines.push('-- self-reference: a listing that moved points at its successor, and the');
lines.push('-- successor may not exist yet on the first pass.');
lines.push('');

const venueRow = (v: Venue, withSuccessor: boolean) => `(
  ${q(v.id)},
  ${q(v.name)},
  ${arr(v.alternateNames)},
  ${q(v.primary.vertical)}::vertical,
  ${q(v.primary.category)},
  ${j(v.secondary)},
  ${n(v.priceTier)},
  ${q(v.neighborhood)},
  ${q(v.address)},
  ${n(v.map.x)},
  ${n(v.map.y)},
  ${q(v.phone)},
  ${q(v.website)},
  ${n(v.rating)},
  ${n(v.reviewCount)},
  ${b(v.claimed)},
  ${b(v.verified)},
  ${n(v.openedYear)},
  ${v.closure ? `${q(v.closure.state)}::closure_state` : 'NULL'},
  ${v.closure ? q(v.closure.note) : 'NULL'},
  ${withSuccessor && v.closure?.successorId ? q(v.closure.successorId) : 'NULL'},
  ${q(v.consumerAlert)},
  ${b(v.promoted ?? false)},
  ${q(v.tagline)},
  ${q(v.about)},
  ${j(v.attributes)},
  ${j(v.meta)},
  ${q(v.defaultMeta.source)}::provenance,
  ${q(v.defaultMeta.updatedAt)}::date,
  ${j(v.schedules)},
  ${j(v.happyHours ?? [])},
  ${j(v.photos)},
  ${j(v.menus)},
  ${j(v.qa)},
  ${j(v.subRatingAverages)},
  ${j(v.busyness ?? {})},
  ${enumArr(v.bookingModes, 'booking_mode')},
  ${q(v.bookingTerms)}
)`;

const venueCols = `insert into venues (
  id, name, alternate_names, primary_vertical, primary_category, secondary,
  price_tier, neighborhood, address, map_x, map_y, phone, website, rating,
  review_count, claimed, verified, opened_year, closure_state, closure_note,
  closure_successor_id, consumer_alert, promoted, tagline, about, attributes,
  attribute_meta, default_source, default_updated_at, schedules, happy_hours,
  photos, menus, qa, sub_rating_averages, busyness, booking_modes, booking_terms
) values`;

lines.push(venueCols);
lines.push(venues.map((v) => venueRow(v, false)).join(',\n'));
lines.push(`on conflict (id) do update set
  name = excluded.name,
  alternate_names = excluded.alternate_names,
  primary_vertical = excluded.primary_vertical,
  primary_category = excluded.primary_category,
  secondary = excluded.secondary,
  price_tier = excluded.price_tier,
  neighborhood = excluded.neighborhood,
  address = excluded.address,
  map_x = excluded.map_x,
  map_y = excluded.map_y,
  phone = excluded.phone,
  website = excluded.website,
  rating = excluded.rating,
  review_count = excluded.review_count,
  claimed = excluded.claimed,
  verified = excluded.verified,
  opened_year = excluded.opened_year,
  closure_state = excluded.closure_state,
  closure_note = excluded.closure_note,
  consumer_alert = excluded.consumer_alert,
  promoted = excluded.promoted,
  tagline = excluded.tagline,
  about = excluded.about,
  attributes = excluded.attributes,
  attribute_meta = excluded.attribute_meta,
  default_source = excluded.default_source,
  default_updated_at = excluded.default_updated_at,
  schedules = excluded.schedules,
  happy_hours = excluded.happy_hours,
  photos = excluded.photos,
  menus = excluded.menus,
  qa = excluded.qa,
  sub_rating_averages = excluded.sub_rating_averages,
  busyness = excluded.busyness,
  booking_modes = excluded.booking_modes,
  booking_terms = excluded.booking_terms;`);
lines.push('');

// Second pass: wire up the successor links now that every row exists.
const moved = venues.filter((v) => v.closure?.successorId);
if (moved.length) {
  lines.push('-- Successor links for listings that moved (F-PROFILE-12).');
  for (const v of moved) {
    lines.push(
      `update venues set closure_successor_id = ${q(v.closure!.successorId!)} where id = ${q(v.id)};`,
    );
  }
  lines.push('');
}

/* ------------------------------------------------------------- table tiers */

const tiers = venues.flatMap((v) => (v.tables ?? []).map((t) => ({ v, t })));
if (tiers.length) {
  lines.push('-- Table service tiers (F-BOOK-06).');
  lines.push(
    'insert into table_tiers (id, venue_id, name, section, minimum_spend, seats, x, y, available) values',
  );
  lines.push(
    tiers
      .map(
        ({ v, t }) =>
          `  (${q(t.id)}, ${q(v.id)}, ${q(t.name)}, ${q(t.section)}, ${n(t.minimumSpend)}, ${n(t.seats)}, ${n(t.x)}, ${n(t.y)}, ${b(t.available)})`,
      )
      .join(',\n'),
  );
  lines.push(`on conflict (id) do update set
  venue_id = excluded.venue_id,
  name = excluded.name,
  section = excluded.section,
  minimum_spend = excluded.minimum_spend,
  seats = excluded.seats,
  x = excluded.x,
  y = excluded.y,
  available = excluded.available;`);
  lines.push('');
}

/* ------------------------------------------------------------------ events */

lines.push('-- Events. Recurring weekly programming carries a weekday; one-offs a date.');
lines.push(
  'insert into events (id, venue_id, title, recurring, weekday, event_date, start_time, end_time, genre, lineup, cover, age_policy, description, ticket_url) values',
);
lines.push(
  events
    .map(
      (e) =>
        `  (${q(e.id)}, ${q(e.venueId)}, ${q(e.title)}, ${b(e.recurring)}, ${
          e.recurring ? n(e.weekday) : 'NULL'
        }, ${e.recurring ? 'NULL' : `${q(e.date)}::date`}, ${q(e.start)}::time, ${q(e.end)}::time, ${q(
          e.genre,
        )}, ${arr(e.lineup)}, ${n(e.cover)}, ${q(e.agePolicy)}, ${q(e.description)}, ${q(e.ticketUrl)})`,
    )
    .join(',\n'),
);
lines.push(`on conflict (id) do update set
  venue_id = excluded.venue_id,
  title = excluded.title,
  recurring = excluded.recurring,
  weekday = excluded.weekday,
  event_date = excluded.event_date,
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  genre = excluded.genre,
  lineup = excluded.lineup,
  cover = excluded.cover,
  age_policy = excluded.age_policy,
  description = excluded.description,
  ticket_url = excluded.ticket_url;`);
lines.push('');

/* ----------------------------------------------------------------- reviews */

// Seeded reviews have no author_id: they predate any real account, and the
// author name is denormalized on the row precisely so they still render.
lines.push('-- Reviews. Seeded rows carry no author_id; author_name is denormalized');
lines.push('-- so they render without a backing account. `recommended = false` rows are');
lines.push('-- the ones the recommendation software excludes from the rating.');
lines.push('-- The seed_key is a stable natural key so re-running is idempotent.');
lines.push('');

const reviewRow = (r: Review) => `  (
    ${q(r.id)},
    ${q(r.venueId)},
    ${q(r.author)},
    ${n(r.authorTrust)},
    ${b(r.elite)},
    ${n(r.rating)},
    ${j(r.subRatings)},
    ${q(r.text)},
    ${q(r.date)}::date,
    ${q(`${r.date}T18:00:00Z`)}::timestamptz,
    ${b(r.edited ?? false)},
    ${n(r.helpful)},
    ${n(r.insightful)},
    ${n(r.funny)},
    ${j(r.tags)},
    ${n(r.photoCount)},
    ${b(r.comped ?? false)},
    ${b(r.recommended)},
    ${r.ownerResponse ? q(r.ownerResponse.text) : 'NULL'},
    ${r.ownerResponse ? `${q(`${r.ownerResponse.date}T12:00:00Z`)}::timestamptz` : 'NULL'}
  )`;

lines.push(`insert into reviews (
  seed_key, venue_id, author_name, author_trust, elite, rating, sub_ratings, body,
  visited_on, created_at, edited, helpful, insightful, funny, tags, photo_count,
  comped, recommended, owner_response, owner_response_at
) values`);
lines.push(reviews.map(reviewRow).join(',\n'));
lines.push(`on conflict (seed_key) do update set
  venue_id = excluded.venue_id,
  author_name = excluded.author_name,
  author_trust = excluded.author_trust,
  elite = excluded.elite,
  rating = excluded.rating,
  sub_ratings = excluded.sub_ratings,
  body = excluded.body,
  visited_on = excluded.visited_on,
  created_at = excluded.created_at,
  helpful = excluded.helpful,
  insightful = excluded.insightful,
  funny = excluded.funny,
  tags = excluded.tags,
  photo_count = excluded.photo_count,
  comped = excluded.comped,
  recommended = excluded.recommended,
  owner_response = excluded.owner_response,
  owner_response_at = excluded.owner_response_at;`);
lines.push('');
lines.push('commit;');
lines.push('');

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join('\n'), 'utf8');

const shortBodies = reviews.filter((r) => r.text.trim().length < 60);
console.log(`Wrote ${outPath}`);
console.log(`  ${venues.length} venues, ${tiers.length} table tiers, ${events.length} events, ${reviews.length} reviews`);
if (shortBodies.length) {
  // Expected. These are the low-effort spam reviews the recommendation software
  // is meant to catch. The 60-character floor is enforced on client submissions
  // by a trigger, not as a table constraint, precisely so the corpus can hold
  // them. Flagged here only so a real short review never slips in unnoticed.
  console.log(
    `  ${shortBodies.length} seeded review(s) below the 60-char submission floor (expected for spam rows):`,
  );
  for (const r of shortBodies) {
    console.log(`    ${r.id} (${r.venueId}): ${r.text.length} chars, recommended=${r.recommended}`);
  }
}
